### ISSUE TITLE
Improvements: a list of channels sorted by number of updates, serving as filters.

### ISSUE THREAD

**Issue by sharethewisdom** [jorenvo/youtube-sub-feed#1]
Hello,
I referenced your script on this [angry reddit page](http://www.reddit.com/r/youtube/comments/37pfmq/youtube_removed_the_option_to_sort_subscriptions). 

If you're interested, would you like to include a sorted list of updated channels on top of the page? (If so, maybe it should be optional.)

I think the API's subscription properties you'd want to look at are `snippet.title` and `contentDetails.newItemCount`. 

A few other thoughts come to mind. Maybe the count of thumbnails _actually on the page_ could be included in parenthesis...
-  16 (8) my subscription
-  12 (8) my other subscription
- 4 (4) yet another one

... or even more useful: why not let it filter a channel's video's by (un)hiding thumbnails?
- [x] 16 (8) - this subscription shows eight thumbs
- [ ] 12 (8) - but my other subscription doesn't
- [x] 4 - this subscription shows four

**Comment by jorenvo** [comment]
Hi,

I'm sorry for not replying sooner. I may have messed up my Github notification settings. Anyway:

> If you're interested, would you like to include a sorted list of updated channels on top of the page? (If so, maybe it should be optional.)

I'm not sure what this would information this would add. You already are able to see a list of updated channels by just looking at the channelnames. I suppose if you have channels uploading a lot of videos it might be useful. I'll think about it. Do you have any specific use cases in which you would find this useful?

> A few other thoughts come to mind. Maybe the count of thumbnails actually on the page could be included in parenthesis...

Not sure what you mean, the amount of thumbnails on the page is constant. So it should always be 8. Or are you talking about grouping videos per channel?

**Comment by jorenvo** [comment]
Closed because of inactivity.
